### ISSUE TITLE
unconverted data remains

### ISSUE THREAD

**Issue by AndyEveritt** [adammhaile/rrgit#1]
Using RRF3.3 On a Duet 3 with Pi I get the following error when cloning a duet.

```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_modul
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\...\MachineConfigs\env\Scripts\
  File "d:\...\machineconfigs\env\lib\site
    cmd.run()
  File "d:\...\machineconfigs\env\lib\site
    remote_files = build_remote_file_map(self.dwa, self.cfg, self.direct
  File "d:\...\machineconfigs\env\lib\site
    fo.getRemoteData(dwa)
  File "d:\...\machineconfigs\env\lib\site-packagesite-packages\rrgit\commands\file_ops.py", line 46, in getRemoteData  
    lm = datetime.strptime(fi['lastModified'], TIMESTAMP_FMT)        
  File "C:\Program Files\Python39\lib\_strptime.py", line 568, in _strptime_datetrptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)   
  File "C:\Program Files\Python39\lib\_strptime.py", line 352, in _strptime      rptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: .4584729+01:00
```

A potential solution may be to implement the sanitising function here https://stackoverflow.com/questions/5045210/how-to-remove-unconverted-data-from-a-python-datetime-object

**Comment by adammhaile** [comment]
LOL - Of **course** the data string format changed in latest versions.
I do not have a Duet I can currently upgrade but I will see if I can fix it soon anyways - may conscript you for testing before final push :)
Oddly, I found another bug just now with my RRF 3.1.1 system.... weird.

**Comment by AndyEveritt** [comment]
Sure, happy to test.
